---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
- name: default
  run_list: ["recipe[sentry-handler-test]"]
  attributes:
    sentry:
      dsn: <%= ENV['SENTRY_HANDLER_DSN'] %>
      verify_ssl: false
